/**
 * API Personajes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PersonajesGet200ResponsePersonajesInner model module.
 * @module model/PersonajesGet200ResponsePersonajesInner
 * @version 1.0.0
 */
class PersonajesGet200ResponsePersonajesInner {
    /**
     * Constructs a new <code>PersonajesGet200ResponsePersonajesInner</code>.
     * @alias module:model/PersonajesGet200ResponsePersonajesInner
     */
    constructor() { 
        
        PersonajesGet200ResponsePersonajesInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PersonajesGet200ResponsePersonajesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PersonajesGet200ResponsePersonajesInner} obj Optional instance to populate.
     * @return {module:model/PersonajesGet200ResponsePersonajesInner} The populated <code>PersonajesGet200ResponsePersonajesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PersonajesGet200ResponsePersonajesInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('nombre')) {
                obj['nombre'] = ApiClient.convertToType(data['nombre'], 'String');
            }
            if (data.hasOwnProperty('casa')) {
                obj['casa'] = ApiClient.convertToType(data['casa'], 'String');
            }
            if (data.hasOwnProperty('descripcion')) {
                obj['descripcion'] = ApiClient.convertToType(data['descripcion'], 'String');
            }
            if (data.hasOwnProperty('rol')) {
                obj['rol'] = ApiClient.convertToType(data['rol'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PersonajesGet200ResponsePersonajesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PersonajesGet200ResponsePersonajesInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['nombre'] && !(typeof data['nombre'] === 'string' || data['nombre'] instanceof String)) {
            throw new Error("Expected the field `nombre` to be a primitive type in the JSON string but got " + data['nombre']);
        }
        // ensure the json data is a string
        if (data['casa'] && !(typeof data['casa'] === 'string' || data['casa'] instanceof String)) {
            throw new Error("Expected the field `casa` to be a primitive type in the JSON string but got " + data['casa']);
        }
        // ensure the json data is a string
        if (data['descripcion'] && !(typeof data['descripcion'] === 'string' || data['descripcion'] instanceof String)) {
            throw new Error("Expected the field `descripcion` to be a primitive type in the JSON string but got " + data['descripcion']);
        }
        // ensure the json data is a string
        if (data['rol'] && !(typeof data['rol'] === 'string' || data['rol'] instanceof String)) {
            throw new Error("Expected the field `rol` to be a primitive type in the JSON string but got " + data['rol']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
PersonajesGet200ResponsePersonajesInner.prototype['id'] = undefined;

/**
 * @member {String} nombre
 */
PersonajesGet200ResponsePersonajesInner.prototype['nombre'] = undefined;

/**
 * @member {String} casa
 */
PersonajesGet200ResponsePersonajesInner.prototype['casa'] = undefined;

/**
 * @member {String} descripcion
 */
PersonajesGet200ResponsePersonajesInner.prototype['descripcion'] = undefined;

/**
 * @member {String} rol
 */
PersonajesGet200ResponsePersonajesInner.prototype['rol'] = undefined;






export default PersonajesGet200ResponsePersonajesInner;

