/**
 * API Personajes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PersonajesGet200ResponsePersonajesInner from './PersonajesGet200ResponsePersonajesInner';

/**
 * The PersonajesGet200Response model module.
 * @module model/PersonajesGet200Response
 * @version 1.0.0
 */
class PersonajesGet200Response {
    /**
     * Constructs a new <code>PersonajesGet200Response</code>.
     * @alias module:model/PersonajesGet200Response
     */
    constructor() { 
        
        PersonajesGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PersonajesGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PersonajesGet200Response} obj Optional instance to populate.
     * @return {module:model/PersonajesGet200Response} The populated <code>PersonajesGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PersonajesGet200Response();

            if (data.hasOwnProperty('personajes')) {
                obj['personajes'] = ApiClient.convertToType(data['personajes'], [PersonajesGet200ResponsePersonajesInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PersonajesGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PersonajesGet200Response</code>.
     */
    static validateJSON(data) {
        if (data['personajes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['personajes'])) {
                throw new Error("Expected the field `personajes` to be an array in the JSON data but got " + data['personajes']);
            }
            // validate the optional field `personajes` (array)
            for (const item of data['personajes']) {
                PersonajesGet200ResponsePersonajesInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/PersonajesGet200ResponsePersonajesInner>} personajes
 */
PersonajesGet200Response.prototype['personajes'] = undefined;






export default PersonajesGet200Response;

