/**
 * API Personajes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiPersonajes);
  }
}(this, function(expect, ApiPersonajes) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiPersonajes.PersonajesGet200ResponsePersonajesInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PersonajesGet200ResponsePersonajesInner', function() {
    it('should create an instance of PersonajesGet200ResponsePersonajesInner', function() {
      // uncomment below and update the code to test PersonajesGet200ResponsePersonajesInner
      //var instance = new ApiPersonajes.PersonajesGet200ResponsePersonajesInner();
      //expect(instance).to.be.a(ApiPersonajes.PersonajesGet200ResponsePersonajesInner);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ApiPersonajes.PersonajesGet200ResponsePersonajesInner();
      //expect(instance).to.be();
    });

    it('should have the property nombre (base name: "nombre")', function() {
      // uncomment below and update the code to test the property nombre
      //var instance = new ApiPersonajes.PersonajesGet200ResponsePersonajesInner();
      //expect(instance).to.be();
    });

    it('should have the property casa (base name: "casa")', function() {
      // uncomment below and update the code to test the property casa
      //var instance = new ApiPersonajes.PersonajesGet200ResponsePersonajesInner();
      //expect(instance).to.be();
    });

    it('should have the property descripcion (base name: "descripcion")', function() {
      // uncomment below and update the code to test the property descripcion
      //var instance = new ApiPersonajes.PersonajesGet200ResponsePersonajesInner();
      //expect(instance).to.be();
    });

    it('should have the property rol (base name: "rol")', function() {
      // uncomment below and update the code to test the property rol
      //var instance = new ApiPersonajes.PersonajesGet200ResponsePersonajesInner();
      //expect(instance).to.be();
    });

  });

}));
